### ISSUE TITLE
Logs export non-functional

### ISSUE THREAD

**Issue by Peter-Petrik** [Saillogger/signalk-saillogger#24]
The download icon on the Logs page `/logs/<id>/` in the top right corner only links to `#` and no function appears to run. Same download icon (just a few pixels bigger in size) on the Moorage list page `/moorages/` executes `/moorages/export/` and provides .gpx output.

Related feature request: Provide .gpx output / download on the individual log display `/log/<id>`

**Comment by itemir** [comment]
There will be a more sophisticated export functionality that will not only export logs but also stays, moorages, maintenance logs etc. 

Can you tell a bit more about how you plan to use this? Current plan is to export all these in a json formatted file.

**Comment by Peter-Petrik** [comment]
Great to hear about the upcoming functionality. It's a great plugin and getting better!

As for the export of individual logs (trips) - the .gpx output can be shared with other cruisers regarding anchorage approaches, navigating around uncharted rocks / obstacles, and more. 

I also like to save locally each individual trip as a .gpx which corresponds with the day's log. I can get such export from the chartplotter, but the setup / consistency of the tracks isn't nearly as intuitive or automated as being able to choose a specific log from saillogger and hit export.

**Comment by itemir** [comment]
Ok this makes sense for track export in GPX. How about other things log details, notes, stay notes, maintenance logs etc. Do you use them?

**Comment by Peter-Petrik** [comment]
Not at the moment, not yet. Still relatively new to saillogger. 

I do have a few suggestions / requests that I can provide either in a new ticket or via email as you prefer.

**Comment by itemir** [comment]
Just released a GPX export function: https://saillogger.com/timelapse/export/

**Comment by Peter-Petrik** [comment]
I was able to use the GPX export function, and it produced the requested file of the trip as GPX. However, the format appears to be one of a route rather than tracks - which is different from what OpenCPN (as an example) expects to display the tracks.

**SailloggerTimelapse.gpx** (name, lat/long, and time have been anonymized)
```
<?xml version="1.0"?>
<gpx version="1.1" creator="Saillogger" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.topografix.com/GPX/1/1" xmlns:gpxx="http://www.garmin.com/xmlschemas/GpxExtensions/v3" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd http://www.garmin.com/xmlschemas/GpxExtensions/v3 http://www8.garmin.com/xmlschemas/GpxExtensionsv3.xsd" xmlns:saillogger="https://saillogger.com">
  <rte>
    <name>Sample name</name>
      <rtept lat="35.1540273" lon="-135.9004466">
      <time>2023-09-27T18:27:44.198000+00:00</time>
      <name>1</name>
      <sym>diamond</sym>
      <type>WPT</type>
    </rtept>
    <rtept lat="35.1540945" lon="-135.9003631">
      <time>2023-09-27T18:27:48.761000+00:00</time>
      <name>2</name>
      <sym>diamond</sym>
      <type>WPT</type>
    </rtept>
```

**Chartplotter tracks GPX export**
```
<?xml version="1.0" encoding="UTF-8"?>
<gpx xmlns="http://www.topografix.com/GPX/1/1" version="1.1" creator="Vulcan AAA XXXXXXXXX" >
    <metadata>
        <time>2023-09-28T02:24:28Z</time>
        <depthunits>meters</depthunits>
        <tempunits>C</tempunits>
        <sogunits>m/s</sogunits>
    </metadata>
    <trk>
        <name> Sample name</name>
        <trkseg>
            <trkpt lon="-135.9004466" lat="35.1540273" >
                <time>2023-09-27T17:46:36Z</time>
                <watertemp>13.39</watertemp>
                <sog>2.10922</sog>
            </trkpt>
            <trkpt lon="-135.9003631" lat="35.1540945" >
                <time>2023-09-27T17:46:37Z</time>
                <watertemp>13.39</watertemp>
                <sog>2.05778</sog>
```

Chartplotter GPX file imported to OpenCPN and exported as GPX
```
<?xml version="1.0"?>
<gpx version="1.1" creator="OpenCPN" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.topografix.com/GPX/1/1" xmlns:gpxx="http://www.garmin.com/xmlschemas/GpxExtensions/v3" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd http://www.garmin.com/xmlschemas/GpxExtensions/v3 http://www8.garmin.com/xmlschemas/GpxExtensionsv3.xsd" xmlns:opencpn="http://www.opencpn.org">
  <trk>
    <name>Sample name</name>
    <extensions>
      <opencpn:guid>abc-abc-xxxx-xxxx-abc012345</opencpn:guid>
      <opencpn:viz>1</opencpn:viz>
    </extensions>
    <trkseg>
      <trkpt lat="35.1540273" lon="-135.9004466">
        <time>2023-09-27T17:46:36Z</time>
      </trkpt>
      <trkpt lat="35.1540945" lon="-135.9003631">
        <time>2023-09-27T17:46:37Z</time>
      </trkpt>
```

**Comment by itemir** [comment]
Yes this follows the OpenCPN route format, it was intentional. Why do you prefer the track?

**Comment by Peter-Petrik** [comment]
The "log" is what happened, thus track seems to be appropriate output. It has date/time as something that's already passed, and OpenCPN can calculate SOG and other relevant info when showing the track. OpenCPN can also produce a route from a track, but not the other way around.

**Comment by itemir** [comment]
Ok, this may need to wait longer then.

**Comment by itemir** [comment]
Actually the difference seems small enough, just changed it. Try again.

**Comment by Peter-Petrik** [comment]
Works great from the initial run, thank you for implementing that so quickly @itemir!

On the export page `/timelapse/export/` when I select "Choose Trips", the names fill in the drop down but the form itself expands beyond the size of the parent `div`. A small cosmetic issue that doesn't affect the functionality.

Out of curiosity, does the "Extremely Granular" selection output all of the collected track points?

**Comment by itemir** [comment]
Can you send a screenshot of that? What kind of device and browser is that?

And yes, extreme exports everything, other options ensure some minimum distance between trackpoints.

**Comment by Peter-Petrik** [comment]
MacOS Ventura with Safari 16.6. This does not occur with Chrome on the same MacOS.

![Export tracks](https://github.com/itemir/signalk-saillogger/assets/4105678/0472a1fe-f1ad-4d0d-b70a-194c64ec39e1)

**Comment by itemir** [comment]
Interesting, I use Ventura and Safari 16.6 too and don't see this.

**Comment by Peter-Petrik** [comment]
I had to choose a trip whose name is longer than the default drop down. In my case, about 60 characters. Then, if I put two fingers on my TouchPad and move them to the side, the whole "inset" shifts.

**Comment by itemir** [comment]
Can you try again?

**Comment by Peter-Petrik** [comment]
I'm still seeing the same behavior.

**Comment by itemir** [comment]
Closing this as this has changed a fair bit. Please re-open if needed.
