### ISSUE TITLE
Upload historical logs

### ISSUE THREAD

**Issue by emonty** [Saillogger/signalk-saillogger#26]
First of all - thanks for this - I've had writing something that's basically what you've already done here for a while - so yay for not having to start from scratch!

Is there any way to upload historical data? I've got an SD card that's been on a YDR device since we got this boat 6 months ago, but I just got saillogger added today. (ohno!) If it would be supported server-side and you can point me in the right direction, I'll happily write up a "read yacht devices log and upload to saillogger" script or something.

**Comment by itemir** [comment]
Thank you for the note. I was just working on an import function for PredictWind and have made some good progress so this may build on it. Can you send that data so we can check the format? Best is to mail to ilker@saillogger.com

**Comment by emonty** [comment]
Absolutely will do! I left my card reader back home and we're out on a mooring ball. I'll send it to you tomorrow when I get back to shore. Thanks!

**Comment by emonty** [comment]
Sadly the memory card I thought was collecting data was, in fact, not. Whoops, bummer.

That said - a GPX or geojson import would also be cool if you were to get around to it.
