### ISSUE TITLE
saillogger plugin update notice 2.4.3

### ISSUE THREAD

**Issue by bgrr74** [Saillogger/signalk-saillogger#27]
Hi Saillogger,

The website gives me a notice that my signal-k plugin version 2.4.2 old is.
But in the plugin section in signal-k there is only version 2.4.2 and no v 2.4.3

Is de plugin update for 2.4.3 availible in the plugin store on the signal-k ?

Greetings Barry

**Comment by itemir** [comment]
2.4.3 is the current version that is being tested but it is not released for broader usage yet. The warning was misleading. Should be  corrected now.

**Comment by itemir** [comment]
BTW, please use the [community forums for support](https://community.saillogger.com).
